(() => {
  'use strict';
  document.addEventListener('DOMContentLoaded',async()=>{
    const programs=await CLMD.load('programs'),grid=document.getElementById('programGrid'),search=document.getElementById('programSearch'),category=document.getElementById('programCategory'),modalEl=document.getElementById('programModal'),modal=bootstrap.Modal.getOrCreateInstance(modalEl);
    CLMD.unique(programs.map(p=>p.category)).forEach(v=>category.insertAdjacentHTML('beforeend',`<option>${CLMD.escape(v)}</option>`));
    const card=p=>`<article class="program-card" id="${p.slug}"><div class="program-image"><img src="${CLMD.asset(p.image)}" alt="${CLMD.escape(p.title)} placeholder" loading="lazy"><span class="program-badge">${CLMD.escape(p.category)}</span></div><div class="program-body"><h3>${CLMD.escape(p.title)}</h3><p>${CLMD.escape(p.narrative)}</p><div class="program-metrics"><div class="program-metric"><strong>${CLMD.number(p.participants)}</strong><span>Participants</span></div><div class="program-metric"><strong>${p.awards}</strong><span>Awards</span></div><div class="program-metric"><strong>${p.sdos}</strong><span>SDOs</span></div></div><button class="btn btn-violet btn-sm mt-3" data-program="${p.slug}">View Accomplishment</button></div></article>`;
    const render=()=>{const q=search.value.toLowerCase(),cat=category.value;const list=programs.filter(p=>(!cat||p.category===cat)&&`${p.title} ${p.category} ${p.narrative}`.toLowerCase().includes(q));grid.innerHTML=list.map(card).join('')||'<div class="content-card text-center">No matching program found.</div>';grid.querySelectorAll('[data-program]').forEach(b=>b.addEventListener('click',()=>open(programs.find(p=>p.slug===b.dataset.program))))};
    const open=p=>{document.getElementById('programModalContent').innerHTML=`<div class="program-image" style="height:360px"><img src="${CLMD.asset(p.image)}" alt="${CLMD.escape(p.title)}"><span class="program-badge">${CLMD.escape(p.category)} · ${p.year}</span></div><div class="p-4 p-lg-5"><span class="section-kicker">Regional accomplishment</span><h2 class="mt-2">${CLMD.escape(p.title)}</h2><p class="text-muted">${CLMD.escape(p.narrative)}</p><div class="row g-3 my-3"><div class="col-4"><div class="program-metric p-3"><strong>${CLMD.number(p.participants)}</strong><span>Participants</span></div></div><div class="col-4"><div class="program-metric p-3"><strong>${p.awards}</strong><span>Awards</span></div></div><div class="col-4"><div class="program-metric p-3"><strong>${p.performance}%</strong><span>Performance</span></div></div></div><h3 class="h6 mt-4">Photo Gallery</h3><div class="gallery-strip mb-4">${p.gallery.map((image,index)=>`<figure><img src="${CLMD.asset(image)}" alt="${CLMD.escape(p.title)} gallery placeholder ${index+1}" loading="lazy"></figure>`).join('')}</div><div class="row g-4"><div class="col-md-6"><h3 class="h6">Highlights</h3><div class="check-list compact">${p.highlights.map(x=>`<div>${CLMD.escape(x)}</div>`).join('')}</div></div><div class="col-md-6"><h3 class="h6">Awardees</h3>${p.awardees.map(x=>`<div class="issuance-row"><strong>${x.rank}</strong><span class="portal-tag">${CLMD.escape(x.awardee)}</span></div>`).join('')}</div></div><p class="small text-muted mt-4 mb-0">Demonstration data and placeholder photography. Replace with validated accomplishment records and official event photos.</p></div>`;modal.show()};
    search.addEventListener('input',CLMD.debounce(render,120));category.addEventListener('change',render);render();
    if(location.hash){const slug=location.hash.slice(1),p=programs.find(x=>x.slug===slug);if(p)setTimeout(()=>open(p),300)}
  });
})();
