(() => {
  'use strict';
  document.addEventListener('DOMContentLoaded',async()=>{
    const data=await CLMD.load('gallery'),grid=document.getElementById('galleryGrid'),search=document.getElementById('gallerySearch'),program=document.getElementById('galleryProgram'),year=document.getElementById('galleryYear'),area=document.getElementById('galleryArea'),division=document.getElementById('galleryDivision'),lightbox=document.getElementById('galleryLightbox');let visible=[],current=0;
    const fill=(el,values)=>CLMD.unique(values.map(String)).forEach(v=>el.insertAdjacentHTML('beforeend',`<option>${CLMD.escape(v)}</option>`));fill(program,data.map(x=>x.program));fill(year,data.map(x=>x.year));fill(area,data.map(x=>x.learningArea));fill(division,data.map(x=>x.division));
    const render=()=>{const q=search.value.toLowerCase();visible=data.filter(x=>(!program.value||x.program===program.value)&&(!year.value||String(x.year)===year.value)&&(!area.value||x.learningArea===area.value)&&(!division.value||x.division===division.value)&&JSON.stringify(x).toLowerCase().includes(q));document.getElementById('galleryCount').textContent=`${visible.length} photo${visible.length===1?'':'s'} found`;grid.innerHTML=visible.map((x,i)=>`<figure class="gallery-item" data-index="${i}"><img src="${CLMD.asset(x.image)}" alt="${CLMD.escape(x.title)}" loading="lazy"><figcaption class="gallery-caption"><strong>${CLMD.escape(x.title)}</strong><span>${CLMD.escape(x.program)} · ${x.year} · ${CLMD.escape(x.division)}</span></figcaption></figure>`).join('')||'<div class="content-card text-center">No gallery item matches the selected filters.</div>';grid.querySelectorAll('[data-index]').forEach(f=>f.addEventListener('click',()=>open(Number(f.dataset.index))))};
    const show=()=>{const item=visible[current];if(!item)return;lightbox.querySelector('img').src=CLMD.asset(item.image);lightbox.querySelector('img').alt=item.title;lightbox.querySelector('figcaption').textContent=`${item.title} — ${item.caption}`};
    const open=i=>{current=i;show();lightbox.classList.add('open');document.body.classList.add('menu-open')};const close=()=>{lightbox.classList.remove('open');document.body.classList.remove('menu-open')};
    lightbox.querySelector('.lightbox-close').addEventListener('click',close);lightbox.querySelector('.prev').addEventListener('click',()=>{current=(current-1+visible.length)%visible.length;show()});lightbox.querySelector('.next').addEventListener('click',()=>{current=(current+1)%visible.length;show()});lightbox.addEventListener('click',e=>{if(e.target===lightbox)close()});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')lightbox.querySelector('.prev').click();if(e.key==='ArrowRight')lightbox.querySelector('.next').click()});
    [search,program,year,area,division].forEach(el=>el.addEventListener(el===search?'input':'change',CLMD.debounce(render,100)));render();
  });
})();
